#174566481 Setup tdd environment with mocha/chai
devcareer/code-jammers-backend pull request #11
Opened 2020-09-01 14:36 UTC by Extremophile-ai

## What does this PR do
   This PR sets up a test driven development (tdd) environment with Mocha/chai for Know Africa.

## Description of tasks to be completed?
 - Set up tdd environment with Mocha/chai to test cod
  - Install Mocha, chai, chai-http from npm
  - Configure package.json with a test script

## How should this be manually tested/checked?
- Clone the PR
- Cd into the branch `ch-set-up-tdd-environment-174566481`
- Install the dependencies using `npm install`
- Run the test on the terminal using `npm run test`
It should show 1 passing

## What are the relevant pivotal tracker stories?
[#174566481](https://www.pivotaltracker.com/story/show/174566481)

2020-09-01 15:59 UTC, Fiyin-Anne approved these changes

2020-09-01 16:51 UTC, codeliezel commented
@Extremophile-ai re-write your PR comment to make it better

2020-09-01 16:53 UTC, bellogo approved these changes
tests ran successfully

2020-09-01 23:07 UTC, Extremophile-ai commented
> @Extremophile-ai re-write your PR comment to make it better

@codeliezel  I've done that. Please take a look at it again

2020-09-02 09:37 UTC, codeliezel reviewed
set up the coverage file by installing dependencies like nyc, etc and add the flags to the test script.
also, the test you wrote should be in another file in the tests file, while you import that file into the index.
Good job.

2020-09-02 15:54 UTC, codeliezel requested changes
@Extremophile-ai  add the reported text file with the HTML file, I expected you to have RESEARCHED and git ignored the coverage folder, also don't name that file `test.js` give it a better name.

good job

2020-09-02 15:58 UTC, Fiyin-Anne approved these changes

2020-09-03 09:11 UTC, codeliezel commented on src/tests/index.js
> +import describe from "./index-test";
this should be `import "./index-test"`

2020-09-03 09:12 UTC, Extremophile-ai commented on src/tests/index.js
> +import describe from "./index-test";
Ok

2020-09-03 09:18 UTC, bellogo approved these changes

2020-09-03 09:23 UTC, Augusta-E approved these changes
kindly put the backticks to indicate the codes

2020-09-03 09:26 UTC, Extremophile-ai commented
> kindly put the backticks to indicate the codes

Done. Thanks!

2020-09-03 09:28 UTC, codeliezel reviewed
Good job

2020-09-03 09:30 UTC, Fiyin-Anne approved these changes

2020-09-03 11:49 UTC, merged