#174626782 Create tourist centers and city models[WIP]
devcareer/code-jammers-backend pull request #19
Opened 2020-09-03 13:03 UTC by Bernard-Namangala

### What does this PR do?

This PR creates city and tourist center models and also creates city and tourist center 

### Description of tasks to be completed?

- create city model
- create tourist center model
- create city migrations
- create tourist centeer migrations
- create city seeders
- create tourist center seeders
- install sequelize
- install sequelize-cli
   
### How should this be manually tested/checked?
Clone the PR and checkout to the branch ft-tourist-centers-cities-models-174626782
    
### What are the relevant pivotal tracker stories?
[#174626782 ](https://www.pivotaltracker.com/n/projects/2463429/stories/174626782)

2020-09-16 21:34 UTC, codeliezel reviewed
Good job all around, make sure whatever changes you make to the models directly affects and updates migrations, and recheck the migrations and seeders properly.

2020-09-16 21:34 UTC, codeliezel commented on src/models/city.js
> +      onDelete: "cascade",
i dont think we need a  `onDelete cascade` fro now, you may remove it

2020-09-16 21:34 UTC, codeliezel commented on src/models/city.js
> +    gallary: {
`gallery`  it should be, you have a wrong spelling..

2020-09-16 21:34 UTC, codeliezel commented on src/models/city.js
> +    location: {
change this location field to `capital`, now, so instead of this model called city, call it **state**, now its a state migration.

2020-09-16 21:34 UTC, codeliezel commented on src/models/city.js
> +    countryId: {
this **countryId** field should be the first field in this model structure and not last.

2020-09-16 21:34 UTC, codeliezel commented on src/models/touristCenter.js
> +    gallary: {
change the spelling to gallery

2020-09-16 21:34 UTC, codeliezel commented on src/models/touristCenter.js
> +    countryId: {
put countryId as the first field

2020-09-16 21:34 UTC, codeliezel commented on src/models/touristCenter.js
> +      onDelete: "cascade",
we do not need the onDelete cacade for now

2020-09-16 21:34 UTC, codeliezel commented on src/models/touristCenter.js
> +module.exports = (sequelize, DataTypes) => {
also, add a `text` field for touristCenter.

2020-09-16 21:40 UTC, codeliezel commented
Also good job again, your PR and PT description is good, so now< i need you to quickly attend to those reviews, get two reviews and approvals from your tms and research on hound, why is hound always complaining?

so we need a `.eslintignore` file in which you will ignore files like this:

```
node_modules/
npm-debug.log
.vscode/**
.nyc_output/
coverage
src/database/
src/models
```

all the files that re no need to be in ou remote repo, ignore them....

2020-09-17 08:18 UTC, Fiyin-Anne approved these changes

2020-09-17 14:20 UTC, balldash approved these changes

2020-09-17 14:49 UTC, codeliezel requested changes
Go and read the reviews I left for you last night. Calm down and don't rush to finish a task without following the feedback and review process. i won't repeat myself, just pray you still find those reviews, if not. I will never merge this task.

2020-09-18 09:13 UTC, balldash approved these changes

2020-09-18 09:57 UTC, md-codes commented on src/database/index.js
> +    url: process.env.DATABASE_URL,
the url should be `process.env.DEV_DATABASE_URL` and insert the key=value in the .env file

2020-09-18 09:57 UTC, md-codes commented on src/database/index.js
> +import dotenv from "dotenv";
Check your database folder structure and the naming conventions: create a config folder in the database folder, move the index.js file to the database>config folder, and rename the index.js file config.js.

2020-09-18 09:57 UTC, md-codes commented on src/database/index.js
> +    url: process.env.DATABASE_URL,
should be url: process.env.TEST_DATABASE_URL and insert the key=value in the .env file

2020-09-18 09:57 UTC, md-codes commented on src/database/migrations/20200906143952-create-tourist-center.js
> +            type: Sequelize.TEXT,
I think the name, location, and the gallery type should be Sequelize.STRING because their contents will not be as long as the TEXT type.

2020-09-18 09:57 UTC, md-codes commented on src/database/migrations/20200906145335-create-state.js
> +            type: Sequelize.TEXT,
The same here too, the capital and gallery...I think the types should be .STRING

2020-09-18 09:57 UTC, md-codes commented on src/models/state.js
> +
The same here too... I think the type should .STRING

2020-09-18 09:57 UTC, md-codes commented on src/models/touristCenter.js
> +  });
Same here, I think the type should be .STRING

2020-09-18 19:15 UTC, Fiyin-Anne approved these changes

2020-09-18 20:19 UTC, codeliezel approved these changes
Good job

2020-09-18 20:21 UTC, merged