#174566179 Prepared app for heroku deployment
devcareer/code-jammers-backend pull request #20
Opened 2020-09-03 13:44 UTC by balldash

What does this PR do?

Creates a heroku environment for the app

Description of Task to be completed?

- create procfile for use on heroku
- create build script to build app on local environment

How should this be manually tested?

After cloning the repo, cd into it and RUN npm install, download the heroku cli and RUN heroku local web

What are the relevant pivotal tracker stories?

#174566179

2020-09-03 21:22 UTC, codeliezel commented
@balldash  install cross-env and use it to set environments, also had a start command in your package.json scripts. Also, your procfile should be `web: npm run start`

2020-09-03 21:22 UTC, codeliezel commented
@balldash also beg team-mates to review and approve, I want all these done before 11 tomorrow

2020-09-03 21:24 UTC, codeliezel commented on package.json
>      "start": "nodemon --exec babel-node ./src/app.js",
install cross-env and use it to set development test and production environments. This line should be "start:dev"

2020-09-03 21:29 UTC, codeliezel requested changes
@balldash go to Heroku dashboard and et automatic deploy to develop branch, and when test passes.. also done forget the PR pipelines and I shouldn't remind you again to write your PT story.

2020-09-03 21:29 UTC, codeliezel commented on src/tests/index-test.js
> +export default describe;
remove this  export default describe` seems, godspower made a mistake

2020-09-04 11:05 UTC, codeliezel commented
@balldash delete your build folder and git ignore it

2020-09-06 02:00 UTC, codeliezel commented
@balldash resolve ur conflicts

2020-09-07 21:22 UTC, balldash commented
> @balldash go to Heroku dashboard and et automatic deploy to develop branch, and when test passes.. also done forget the PR pipelines and I shouldn't remind you again to write your PT story.

@codeliezel I need admin privileges to setup automatic deployment and PR pipelines

2020-09-08 08:10 UTC, balldash commented
> @balldash go to Heroku dashboard and et automatic deploy to develop branch, and when test passes.. also done forget the PR pipelines and I shouldn't remind you again to write your PT story.

@codeliezel I need admin access to do this

2020-09-08 13:28 UTC, Fiyin-Anne reviewed
How do I download the heroku cli and run heroku local?

2020-09-08 13:37 UTC, balldash commented
> How do I download the heroku cli and run heroku local?

@Fiyin-Anne use this link: https://devcenter.heroku.com/articles/heroku-cli

2020-09-08 13:38 UTC, codeliezel commented
> How do I download the heroku cli and run heroku local?

@Fiyin-Anne i don't think we need to do that again! @balldash please update your PR

2020-09-08 13:45 UTC, balldash commented
> > How do I download the heroku cli and run heroku local?
> 
> @Fiyin-Anne i don't think we need to do that again! @balldash please update your PR description.

@codeliezel I've updated the PR description

2020-09-08 13:50 UTC, codeliezel commented
> > > How do I download the heroku cli and run heroku local?
> > 
> > 
> > @Fiyin-Anne i don't think we need to do that again! @balldash please update your PR description.
> 
> @codeliezel I've updated the PR description

Good job

2020-09-08 13:51 UTC, Bernard-Namangala reviewed
Works fine just remove the other procfile because there are two procfiles

2020-09-08 13:51 UTC, Fiyin-Anne submitted a review, later dismissed

2020-09-08 13:57 UTC, codeliezel reviewed
- remove the procfile with the small p...
- Its only one procfile you should have!

2020-09-08 14:12 UTC, md-codes approved these changes

2020-09-08 14:12 UTC, balldash commented
> * remove the procfile with the small p...
> * Its only one procfile you should have!

@codeliezel I have removed it

2020-09-08 14:19 UTC, balldash commented
> Works fine just remove the other procfile because there are two procfiles

@Bernard-Namangala I have removed the duplicate procfile

2020-09-08 14:31 UTC, donaldcrane approved these changes
Great it works!!

2020-09-08 14:46 UTC, codeliezel approved these changes
good job!

2020-09-08 14:46 UTC, merged