#174626493 Build User and Profile Models [WIP]
devcareer/code-jammers-backend pull request #24
Opened 2020-09-03 15:27 UTC by md-codes

### What doesthis PR do? 
This PR designs the sequelize models with migrations and seeders for user and profile 

## Description of tasks to be completed?
- Create sequelize models for user and profile 
- Create migrations 
- Create the database seeders 

## How should this be manually tested/checked? 
- Clone the PR 
- Cd into the branch cd ft-build-mod-mig-174626493 

What are the relevant pivotal tracker stories?
[#174626493](https://www.pivotaltracker.com/n/projects/2463429/stories/174626493)

2020-09-08 12:36 UTC, Endowmissy requested changes
@md-codes Add id to User Model

2020-09-10 10:13 UTC, donaldcrane submitted a review, later dismissed
Nice! it works, good work.

2020-09-10 10:54 UTC, AbonyiXavier submitted a review, later dismissed

2020-09-10 11:53 UTC, Augusta-E commented
Please kindly remove the WIP for us to know that you are done.

2020-09-10 12:29 UTC, Extremophile-ai approved these changes

2020-09-10 12:46 UTC, Augusta-E commented
Great work, your test works fine but I couldn't run your migrations and seeders, I figure it's because you didn't include the database path in your .sequelize file because I was able to run it when I included it.

2020-09-10 13:31 UTC, bellogo approved these changes

2020-09-10 13:32 UTC, donaldcrane approved these changes

2020-09-10 13:37 UTC, Augusta-E approved these changes

2020-09-10 16:13 UTC, codeliezel requested changes
Please have a command for migrations and seeders, whereby I can just run `npm run migrate` and it runs and also `npm run seed` and it seeds!
very important before anybody can test your code.

2020-09-10 16:13 UTC, codeliezel commented on src/models/profile.js
> +        Profile.associate = (models) => {
You do not need a profile belongs to again, since you already have an association for user, remove this...

2020-09-10 16:13 UTC, codeliezel commented on src/models/user.js
> +    id: {
you do not need an Id object in models, remove it

2020-09-10 16:13 UTC, codeliezel commented on src/models/user.js
> +  User.associate = (models) => {
improve  your associations to be better...
making sure it includes an `as` keyword and the `foreign key`, also remove the onDelete, a user can field can never be deleted

2020-09-10 16:13 UTC, codeliezel commented on src/models/profile.js
> +        id: {
remove the id object

2020-09-10 16:13 UTC, codeliezel commented on src/models/profile.js
> +        userId: {
transfer this to be the first field

2020-09-10 16:13 UTC, codeliezel commented on src/models/user.js
> +    role: {
have an enum data type that specifies the four users in the app; something like this ; e.g
```
 type: DataTypes.ENUM('Super Admin', 'Travel Admin', 'Manager', 'Staff') in the role object
```

2020-09-10 16:14 UTC, codeliezel commented
And what does this mean? `Do npm test on the terminal.` to do what exactly?? Please update your PR description and make it perfect!

2020-09-10 16:19 UTC, codeliezel reviewed
Please make all the changes I have put here. good luck

2020-09-10 16:19 UTC, codeliezel commented on src/models/user.js
> +
have an `isVerified` field after this and ensure that the boolean default is false.

2020-09-10 16:19 UTC, codeliezel commented on src/migrations/20200903160620-create-user.js
> +    await queryInterface.createTable('Users', {
replace this line with something like this

```
export default {
  up(queryInterface, Sequelize) {
    return queryInterface.sequelize.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";').then(() => queryInterface.createTable('Users', {

we are using uuid for our ids

- make these changes in all migrations too.
```

2020-09-10 16:19 UTC, codeliezel commented on src/seeders/20200904133535-User.js
> +      email: 'olusola@gmail.com',
in all your seeders, have the ids included there, even the foreign ids... you can get fake ids(uuid) here

https://www.uuidgenerator.net/version4

2020-09-14 08:53 UTC, codeliezel reviewed
your `hasOne` association test is failing... please fix it.

2020-09-14 09:01 UTC, codeliezel commented
delete the unused index.js file in your test/models folder
also, why are you not importing models.profile in the index.test file

2020-09-14 09:05 UTC, codeliezel commented
@md-codes also change your associations to a profile `belongs to` a user. 
- user model should not have any ass at all
-

2020-09-14 09:43 UTC, md-codes commented
> delete the unused index.js file in your test/models folder
> also, why are you not importing models.profile in the index.test file

I am testing the models.profile in the tests>model>profile.js file.

2020-09-14 10:15 UTC, codeliezel reviewed
> > delete the unused index.js file in your test/models folder
> > also, why are you not importing models.profile in the index.test file
> 
> I am testing the models.profile in the tests>model>profile.js file.

I know, then import it in the **index.test.js**

if you are confused, ask @Extremophile-ai 
-

2020-09-14 15:43 UTC, codeliezel commented
i dont like this in your migrations, 
```
firstName: { type: Sequelize.STRING },
      lastName: { type: Sequelize.STRING },
      profilePicture: { type: Sequelize.STRING },
      createdAt: { allowNull: false, type: Sequelize.DATE },
      updatedAt: { allowNull: false, type: Sequelize.DATE },
    }));
```
break it down like the models..

- Also, I am getting this error when I try to migrate: `ERROR: foreign key constraint "Profile_userId_fkey" cannot be implemented`
-  ```
userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
```

The above code should be STRING and not INTEGER

- also, get two of your tms to review and approve before I finally approve.

2020-09-14 19:44 UTC, codeliezel commented
I still keep getting this error `ERROR: foreign key constraint "Profile_userId_fkey" cannot be implemented`

2020-09-14 19:48 UTC, codeliezel commented
exclude your models in your `.codeclimate.yml` file please.

2020-09-14 19:52 UTC, codeliezel commented
Add this in your userid file in models after allowNull

```
references: {
        model: "Users",
        key: "id",
      },
```

2020-09-14 19:53 UTC, codeliezel commented
in your user migration file, in the role field, also add the ENUM values just like the model.

2020-09-15 12:05 UTC, Augusta-E reviewed
All tests passed, migration is working well but your data are not seeding into db... It's returning the error "ERROR: relation "Profiles" does not exist"
I figured you used Profile in migration and Profiles in seeders...

 `await queryInterface.bulkInsert("Profiles", [{`

when I removed the 's' from the 'profiles' in the above line of code in profile.js file, seeders, it worked fine

2020-09-15 15:37 UTC, Augusta-E approved these changes

2020-09-15 15:50 UTC, Fiyin-Anne submitted a review, later dismissed

2020-09-15 17:28 UTC, codeliezel commented on src/database/seeders/20200904133732-Profile.js
> +      userId: 1,
let the userid on profile seeders be the same id as the id of users in user seeders

2020-09-16 09:55 UTC, Fiyin-Anne approved these changes

2020-09-16 09:59 UTC, balldash approved these changes

2020-09-16 10:04 UTC, codeliezel approved these changes
Good job

2020-09-16 10:05 UTC, merged