#174566160 create user account [WIP]
devcareer/code-jammers-backend pull request #25
Opened 2020-09-07 10:24 UTC by Extremophile-ai

## What does this PR do ##
This PR creates a user account

## Description of tasks to be completed? ##
- Install relevant dependencies
- Initialize them
- Write program to create a user
- Test program to ensure user is created successfully

## How should this be manually tested/checked? ##
- Clone the PR
- Cd into the branch `ft-user-sign-up-174566160`
- Install the dependencies using npm install
- Start the server by running `npm run dev`
- Test the post route using using Postman 
- A user must have sign up with a username, an email and a password

## What are the relevant pivotal tracker stories? ##
[#174566160](https://www.pivotaltracker.com/story/show/174566160)

2020-09-10 15:16 UTC, AbonyiXavier reviewed
1. Please you need to check for a duplicate of email been signed up with using sequelize `findOne` method, just to avoid same email been used.

2. Please remove your test from index-test file, create a `user.js` file and put your signup test inside

2020-09-10 15:18 UTC, Extremophile-ai commented
> 1. Please you need to check for a duplicate of email been signed up with using sequelize `findOne` method, just to avoid same email been used.
> 2. Please remove your test from index-test file, create a `user.js` file and put your signup test inside

Alright

2020-09-16 22:05 UTC, codeliezel reviewed
- the Jwt.js file should be in utilities.
- the user service file should be in services folder, create a services folder in the src folder and have something like this;

**src/services/userService.js**

- why don't you have an error 409 email conflict test?
- create a controllers file in tests and add controllers test there, also move all models tests in a folder called models..

Good job for now...

2020-09-17 08:10 UTC, Extremophile-ai commented on src/UserService/Jwt.js
> +import jwt from "jsonwebtoken";
Ok...

2020-09-17 08:13 UTC, Extremophile-ai commented on src/UserService/User.js
> +import database from "../models";
Ok.
Done

2020-09-21 11:51 UTC, Augusta-E submitted a review, later dismissed

2020-09-21 12:09 UTC, donaldcrane approved these changes

2020-09-21 14:19 UTC, Fiyin-Anne approved these changes

2020-09-22 09:20 UTC, Fiyin-Anne approved these changes

2020-09-22 09:20 UTC, Augusta-E submitted a review, later dismissed

2020-09-22 09:21 UTC, bellogo approved these changes

2020-09-23 11:08 UTC, Endowmissy reviewed
@Extremophile-ai in the seed file, encrypt password.
work on username and password validation because as a user I can sign up if I put spaces in my username and password, so that needs to be fixed, your validation should also fix extra spaces
return all messages at once and it should be in JSON format

2020-09-23 11:36 UTC, Extremophile-ai commented
> @Extremophile-ai in the seed file, encrypt password.
> work on username and password validation because as a user I can sign up if I put spaces in my username and password, so that needs to be fixed, your validation should also fix extra spaces
> return all messages at once and it should be in JSON format

Ok.

2020-09-24 09:12 UTC, Fiyin-Anne approved these changes

2020-09-24 10:22 UTC, donaldcrane approved these changes

2020-09-24 16:45 UTC, Bernard-Namangala submitted a review, later dismissed

2020-09-27 10:01 UTC, codeliezel requested changes
When I try to sign up different users, it asks for different secret keys, I don't like that, pls change it. Also, create a sample test format on your PR on how to test the API, where to put our secret ket in env, all that info..... add it.

2020-09-27 10:07 UTC, codeliezel commented
Ok i get why must JWT_KEY = secret instead of secret = <a value>

2020-09-27 10:11 UTC, Extremophile-ai commented
> Ok i get why must JWT_KEY = secret instead of secret =

Yes, the JWT_KEY = secret should be in the .env file.
and it is there on the PR description

2020-09-28 12:03 UTC, Fiyin-Anne approved these changes

2020-09-28 12:34 UTC, donaldcrane approved these changes

2020-09-28 14:00 UTC, codeliezel approved these changes

2020-09-28 14:15 UTC, merged