feat(Signup/Signin using Google)[WIP]
devcareer/code-jammers-backend pull request #31
Opened 2020-09-16 13:04 UTC by AbonyiXavier

**What does this PR do**
- This PR enables User to  signup and sign in with google OAuth feature

**Description of tasks to be completed?**
- Install relevant dependencies using `npm install`
- Write a program to  signup and sign in a user using google oauth
- Test program to ensure the user is signed in successfully

**How should this be manually tested/checked?**
- Clone the PR
- Cd into the branch ft-user-sign-in-174566162
- Install the dependencies using `npm install`
- Start the server by running `npm run dev`

**What are the relevant pivotal tracker stories?**
[#174838693](https://www.pivotaltracker.com/story/show/174838693)

2020-09-28 18:32 UTC, codeliezel requested changes
Why have you not rebase, also before pushing your code, lint them very very well? Why is code climate also shouting.

2020-09-28 18:32 UTC, codeliezel commented on src/database/config/passport.js
> +import { Strategy } from "passport-google-oauth20";
Now for this config, you don't need to add it to database -> config again, just add it to config-> config. that is where it should be. they are not db files.

2020-09-28 18:32 UTC, codeliezel commented on src/models/user.js
> +    // role: {
this is wrong, please don't send commented out code to a codebase again.

2020-09-30 15:07 UTC, codeliezel requested changes
Now, maybe you don't get the requirements for this PR. 

- the OAuth is not signing me up, it's meant to if I am a first time user
- then if it's that I'm signed up already, and I try signing up with my google, it should bring out an error that user exists.
- then as a user is signing up, I want to see the data in the DB. The data has to be filled in the users table to confirm if a user has signed up.

2020-09-30 15:08 UTC, codeliezel commented
when I use this link again: `http://localhost:3000/auth/google/callback`
- I get this error
![dev1](https://user-images.githubusercontent.com/35759534/94703834-2e4fd300-0337-11eb-966b-5b2032c2b60c.PNG)

2020-11-13 12:02 UTC, bellogo approved these changes

2020-11-13 12:02 UTC, balldash submitted a review, later dismissed

2020-11-13 23:39 UTC, donaldcrane submitted a review, later dismissed

2020-11-14 06:12 UTC, bellogo approved these changes

2020-11-14 16:24 UTC, codeliezel approved these changes

2020-11-14 16:26 UTC, merged