#174838707 A user should be able to reset their password [WIP]
devcareer/code-jammers-backend pull request #33
Opened 2020-09-18 13:11 UTC by balldash

### What does this PR do?
Allow users to reset their passwords

### Description of the Task to be completed?
A user should be able to reset their password if they signed up using their email

### How should this be manually tested?
[WIP]
### What are the relevant pivotal tracker stories?

[#174838707](https://www.pivotaltracker.com/story/show/174838707)

2020-10-27 10:33 UTC, Extremophile-ai requested changes

2020-10-27 10:33 UTC, Extremophile-ai commented on src/controllers/resetPasswordController.js
> +        } catch (error) {
I think the status code here is wrong.
A more appropriate statusCode should be 500 for server error or 409 for conflict

2020-10-27 10:38 UTC, Extremophile-ai requested changes
I think the status code here is wrong.
A more appropriate statusCode should be 500 for server error or 409 for conflict

2020-10-27 10:38 UTC, Extremophile-ai commented on src/controllers/resetPasswordController.js
> +        } catch (error) {
I think the status code here is wrong.
A more appropriate statusCode should be 500 for server error or 409 for conflict

2020-10-27 10:41 UTC, Extremophile-ai requested changes
Your use of status code in your resetPasswordController is wrong.

Kindly research on statuscodes and use as appropriate

2020-10-28 13:37 UTC, Extremophile-ai submitted a review, later dismissed
Requested changes has been made.

But one of your test is failing.

2020-11-02 13:29 UTC, Fiyin-Anne approved these changes

2020-11-02 13:31 UTC, bellogo approved these changes

2020-11-02 15:35 UTC, codeliezel approved these changes

2020-11-02 15:35 UTC, codeliezel commented on src/tests/controllers/resetPasswordTest/reset-test-data.js
> +  // toJSON: () => ({
remove this commented code

2020-11-02 15:35 UTC, codeliezel commented on src/controllers/resetPasswordController.js
> +let hostURL;
you are not using this, you can remove it `let hostURL;`

2020-11-02 15:36 UTC, merged