#174838381 Build an API for a user to update his/her profile
devcareer/code-jammers-backend pull request #34
Opened 2020-09-18 13:11 UTC by md-codes

## What does this PR do ##
This PR allows the user to edit and update his/her profile successfully.

## Description of tasks completed? ##
- Create an update user profile route and controller
- Write tests to ensure the user can update their profile successfully

## How should this be manually tested/checked? ##
- Clone the PR
- Checkout to the branch `ft-edit-profile-174838381`
- Install the dependencies using `npm install`
- Create a `.env file` and define the following as follows:
   - `DEV_DATABASE_URL = <development database url>`
   - `TEST_DATABASE_URL = <test database url>`
   - `DATABASE_URL = <production database url>`
- run ```npm run migrate``` to create the database tables
- run ```npm run seed``` to seed the database
- Start the server by running ```npm run start-dev```
- Sign in via `http://localhost:3000/api/v1/users/signin` using a `POST` method with
```
          {
          "email": "godspower@gmail.com",
          "password": "12345"
           }
```
and copy the token (without the quotes) from the response body.
- In a new tab, under the `Authorization` tab, change the `TYPE` to `Bearer Token` and paste the token in the space available.
- Make a `PATCH` request to `http://localhost:3000/api/v1/user-profile` and place the fields to be updated in the request body.
    - request body sample:
```
{
    "firstName": "Ufuoma",
    "lastName": "Ogodo",
    "profilePicture": "https://www.instagram.com/_bellogo/"
}
```
### Link to architecture
[architecture](https://docs.google.com/document/d/1crqaDdvRTjx5XsvxZtEjomS4hKtruSCkizo5Bho10Xg/edit?usp=sharing)

## What are the relevant pivotal tracker stories? ##
[#174838381](https://www.pivotaltracker.com/story/show/174838381)

2020-10-30 18:45 UTC, Fiyin-Anne approved these changes

2020-11-01 21:58 UTC, Extremophile-ai approved these changes

2020-11-01 21:59 UTC, Fiyin-Anne approved these changes

2020-11-02 09:43 UTC, codeliezel requested changes
It works but there is a problem when I try to put another person's sign-in token. It still updates the user for me.
if I put GP's token to update Ufuom's profile. it is meant to deny me access.
please work on this and get two reviews from tms..:)

2020-11-02 12:08 UTC, codeliezel approved these changes

2020-11-02 12:10 UTC, merged