fix signup credentials [WIP]
devcareer/code-jammers-backend pull request #39
Opened 2020-09-30 05:21 UTC by Extremophile-ai

2020-10-09 23:03 UTC, Fiyin-Anne approved these changes

2020-10-09 23:03 UTC, bellogo approved these changes

2020-10-10 16:37 UTC, codeliezel requested changes
please quickly work on that review and let two tms review and approve

2020-10-10 16:37 UTC, codeliezel commented on .env.sample
> +//   production: {
why are you pushing commented code?

2020-10-10 17:18 UTC, Fiyin-Anne approved these changes

2020-10-10 17:24 UTC, AbonyiXavier approved these changes

2020-10-10 18:00 UTC, codeliezel approved these changes

2020-10-10 18:47 UTC, merged