#175537347 Build API for food
devcareer/code-jammers-backend pull request #44
Opened 2020-11-02 15:19 UTC by Extremophile-ai

2020-11-05 12:57 UTC, bellogo commented
When adding food, could you please put the country name in the req.params instead of the req.body

2020-11-05 18:43 UTC, Fiyin-Anne approved these changes

2020-11-06 08:11 UTC, Fiyin-Anne approved these changes

2020-11-06 11:30 UTC, bellogo submitted a review, later dismissed

2020-11-06 16:54 UTC, Fiyin-Anne submitted a review, later dismissed

2020-11-06 17:13 UTC, Fiyin-Anne submitted a review, later dismissed

2020-11-06 17:24 UTC, bellogo approved these changes

2020-11-06 20:54 UTC, codeliezel requested changes
Rework those reviews

2020-11-06 20:54 UTC, codeliezel commented on src/controllers/food/food.js
> +        country,
Please use the ID instead.

2020-11-06 20:54 UTC, codeliezel commented on src/routes/foodRoute/foodRoutes.js
> +router.get("/food/country-foods/:country", getFoodsByCountry);
Just link it the way your tms did.

2020-11-06 20:54 UTC, codeliezel commented on src/routes/foodRoute/foodRoutes.js
> +router.post("/admin/food", verifyToken, verifyAdmin, createFood);
with the countryID

2020-11-06 20:54 UTC, codeliezel commented on src/services/AdminServices/countryService.js
> +=======
you have conflict markers here

2020-11-06 22:36 UTC, Extremophile-ai commented on src/controllers/food/food.js
> +        country,
Done

2020-11-06 22:37 UTC, Extremophile-ai commented on src/routes/foodRoute/foodRoutes.js
> +router.post("/admin/food", verifyToken, verifyAdmin, createFood);
done

2020-11-06 22:37 UTC, Extremophile-ai commented on src/services/AdminServices/countryService.js
> +=======
fixed

2020-11-07 11:54 UTC, bellogo approved these changes

2020-11-07 14:07 UTC, Fiyin-Anne approved these changes

2020-11-07 16:27 UTC, bellogo approved these changes

2020-11-07 16:30 UTC, Fiyin-Anne approved these changes

2020-11-07 19:59 UTC, codeliezel approved these changes

2020-11-07 20:00 UTC, merged