Build CRUD API for music
devcareer/code-jammers-backend pull request #46
Opened 2020-11-02 15:45 UTC by bellogo

2020-11-05 12:45 UTC, donaldcrane submitted a review, later dismissed

2020-11-05 12:45 UTC, Bernard-Namangala approved these changes

2020-11-05 12:48 UTC, Extremophile-ai approved these changes

2020-11-05 12:56 UTC, balldash approved these changes

2020-11-05 17:02 UTC, codeliezel requested changes
Finally, add a field in the music model called information to tell us more about that category of music.

2020-11-05 18:02 UTC, Fiyin-Anne approved these changes

2020-11-05 18:24 UTC, Extremophile-ai submitted a review, later dismissed

2020-11-06 11:47 UTC, donaldcrane approved these changes

2020-11-06 11:48 UTC, Fiyin-Anne approved these changes

2020-11-06 11:52 UTC, Extremophile-ai approved these changes

2020-11-06 12:27 UTC, balldash approved these changes

2020-11-06 13:59 UTC, codeliezel approved these changes

2020-11-06 13:59 UTC, merged