#175541724 Build feature to allow user to add a comment
devcareer/code-jammers-backend pull request #48
Opened 2020-11-02 19:01 UTC by Bernard-Namangala

## What does this PR do ##
-  enables user to add a comment

### Description of tasks to be completed? ###
- create add comment controller
- create add comment route
- write add comment tests

### How should this be manually tested/checked? ###
- Clone the PR
- Checkout to the branch `ft-user-should-be-able-to-comment-175541724`
- Install the dependencies using `npm install`
- Create a `.env file` and define the following as follows:
   - `DEV_DATABASE_URL = <development database url>`
   - `TEST_DATABASE_URL = <test database url>`
   - `DATABASE_URL = <production database url>`
- run ```npm run migrate``` to create the database tables
- run ```npm run seed``` to seed the database
- Start the server by running ```npm run start-dev```
- Sign in via `http://localhost:3000/api/v1/users/signin` using a `POST` method with
```
     {
          "email": "ufuoma@gmail.com",
          "password": "12345"
     }
```
and copy the token (without the quotes) from the response body.

- paste the token in the authorization header
- make a POST request to the url http://127.0.0.1:3000/api/v1/comment with request body {"comment":"I am a test comment"}
- check database comment should be added

### Link to architecture
[architecture]()

### What are the relevant pivotal tracker stories?
[ #175541724](https://www.pivotaltracker.com/story/show/175541724)

2020-11-04 12:54 UTC, donaldcrane commented
bernard, after adding my comment to the database, i didn't get that the comment id so i wasn't able to retrieve the comment back with the get request, the url you pasted was for a comment already on the database...

2020-11-04 13:00 UTC, balldash submitted a review, later dismissed

2020-11-05 09:25 UTC, balldash submitted a review, later dismissed

2020-11-05 09:59 UTC, Extremophile-ai commented on src/controllers/commentController.js
> +    }
No server error?

2020-11-05 11:28 UTC, donaldcrane approved these changes

2020-11-05 16:55 UTC, codeliezel requested changes
So now, let comments reference all the models.
- so now a user can add a comment on any country, tourist centre, state, etc.(very crucial)
- the others, they can GET, PATCH, GET ALL, DELETE using the ids of the created comments.

2020-11-05 16:55 UTC, codeliezel commented on src/controllers/commentController.js
> +const commentController = {
Is there a specific reason why you used constants instead of classes and static methods?

2020-11-05 16:55 UTC, codeliezel commented on src/controllers/commentController.js
> +    const { id } = req.decoded.user;
Users should be able to **comment under a country** you are not referencing any country here. Comments have to reference the countries using appropriate associations.

2020-11-11 10:07 UTC, bellogo reviewed
rename your commentController file to just comment since its already inside a folder named controller

2020-11-13 11:01 UTC, balldash approved these changes

2020-11-13 11:01 UTC, bellogo approved these changes

2020-11-13 11:02 UTC, codeliezel approved these changes

2020-11-13 11:04 UTC, merged

2020-11-14 07:53 UTC, codeliezel commented
@donaldcrane Okay, I have gone through your code and gotten it well.