#175449628 Build CRUD API for Ethnic Groups
devcareer/code-jammers-backend pull request #49
Opened 2020-11-02 19:09 UTC by Fiyin-Anne

## What does this PR do ##
-  enables a user to get a culture by id 
-  enables a user to get all cultures
- enables admin to edit an existing culture in the database
- enables admin to delete a culture from the database

### Description of tasks to be completed? ###
- create a route to get a culture by id
- create a route to get multiple cultures
- create a route to delete a culture by id
- create a route to edit a cultures
- create a controller to get a culture by id
- create a controller to get multiple cultures
- create a controller to delete a culture by id
- create a controller to edit a cultures
- write tests for the controllers and routes

### How should this be manually tested/checked? ###
- Clone the PR
- Checkout to the branch `ft-get-edit-delete-cultures-175449628`
- Install the dependencies using `npm install`
- Create a `.env file` and define the following as follows:
   - `DEV_DATABASE_URL = <development database url>`
   - `TEST_DATABASE_URL = <test database url>`
   - `DATABASE_URL = <production database url>`
- run ```npm run migrate``` to create the database tables
- run ```npm run seed``` to seed the database
- Start the server by running ```npm run start-dev```

### Link to architecture
[architecture]()

### What are the relevant pivotal tracker stories?
[ #175449628](https://www.pivotaltracker.com/story/show/175449628)

2020-11-04 12:49 UTC, balldash submitted a review, later dismissed

2020-11-04 23:30 UTC, bellogo approved these changes

2020-11-05 10:27 UTC, Extremophile-ai approved these changes

2020-11-05 16:40 UTC, codeliezel requested changes
Good job, work on the few reviews.

2020-11-05 16:40 UTC, codeliezel commented on src/controllers/ethnicGroup.js
> +  static async getAll(req, res) {
what is `getAll`? Please put proper names for your methods

2020-11-05 16:40 UTC, codeliezel commented on src/controllers/ethnicGroup.js
> +  static async getById(req, res) {
Please put proper names for your methods

2020-11-05 16:40 UTC, codeliezel commented on src/controllers/ethnicGroup.js
> +  static async deleteById(req, res) {
Please put proper names for your methods

2020-11-05 16:40 UTC, codeliezel commented on src/controllers/ethnicGroup.js
> +  static async updateById(req, res) {
Please put proper names for your methods

2020-11-05 16:40 UTC, codeliezel commented on src/controllers/ethnicGroup.js
> +      if (name) {
we do not need this body of code
```
  if (name) {
        ethnicGroupName = String(name)[0].toUpperCase() + String(name).slice(1).toLowerCase();
      }
``

2020-11-05 16:44 UTC, codeliezel commented
@Fiyin-Anne also it seems this is not in use `getByCountryId`

2020-11-05 17:24 UTC, Fiyin-Anne commented
> @Fiyin-Anne also it seems this is not in use `getByCountryId`

No, it's not

2020-11-05 17:57 UTC, bellogo approved these changes

2020-11-05 18:17 UTC, Extremophile-ai approved these changes

2020-11-05 19:41 UTC, codeliezel approved these changes

2020-11-05 19:43 UTC, merged