#175557405 Build feature to allow an admin activate or deactivate a user
devcareer/code-jammers-backend pull request #50
Opened 2020-11-03 14:14 UTC by donaldcrane

## What does this PR do ##
-  enables Admin to activate or deactivate a user

### Description of tasks to be completed? ###

### How should this be manually tested/checked? ###
- Clone the PR
- Checkout to the branch `ft-user-should-be-able-to-comment-175541724`
- Install the dependencies using `npm install`
- Create a `.env file` and define the following as follows:
   - `DEV_DATABASE_URL = <development database url>`
   - `TEST_DATABASE_URL = <test database url>`
   - `DATABASE_URL = <production database url>`
- run ```npm run migrate``` to create the database tables
- run ```npm run seed``` to seed the database
- Start the server by running ```npm run start-dev```
- Sign in via `http://localhost:3000/api/v1/users/signin` using a `POST` method with
```
     {
          "email": "ufuoma@gmail.com",
          "password": "12345"
     }
```
and copy the token (without the quotes) from the response body.

- paste the token in the authorization header

### Link to architecture
[architecture]()

### What are the relevant pivotal tracker stories?
[ #175557405](https://www.pivotaltracker.com/story/show/175557405)

2020-11-13 23:23 UTC, AbonyiXavier approved these changes

2020-11-14 05:04 UTC, Extremophile-ai approved these changes
Please add a standard commit message

2020-11-14 07:21 UTC, codeliezel requested changes
instead of having a controller called `admin`, put your methods, `deactivate user` and `activate user` in the users' controllers file.

KeyNOTE: verifyUserByID is only allowed for Bernard's, Anything out of it should be `verifyAdmin`

2020-11-14 07:21 UTC, codeliezel commented on src/routes/resetPasswordRoutes.js
> +router.post("/users/recover", verifyUserByDetails, resetPasswordController.recover);
why are these changed to verifyUserbyID ????? what happened to what was there before?

2020-11-14 07:21 UTC, codeliezel commented on src/routes/userRoute/userRoutes.js
> +const { verifyToken, verifyUserById } = Authentication;
change everything back to what was there before. I suppose that is `verifyAdmin`

2020-11-14 07:21 UTC, codeliezel commented on src/controllers/user/user.js
> +        return res.status(403).send({ message: "Sorry User has been De-activated, Please contact an admin." });
instead of send, change all these messages or errors to JSON format. 
```
{
"status": <status-code>,
"error": <error-message>
}
```

2020-11-14 07:21 UTC, codeliezel commented on src/controllers/user/user.js
>        if (!user.verified) {
change to JSON, and follow the format I left below.

2020-11-14 07:31 UTC, codeliezel commented
I just want a method/function in the middleware whereby, it checks for whether a user is activated or not, now that function can be put into major routes. This will automatically solve your problem.

for example:
`router.patch("/user-profile/", verifyToken, checkUserStatus, userController.updateUserProfile);`

OR

`router.patch("/comment/:id", verifyToken, verifyUserById, checkUserStatus, updateComment);`

2020-11-14 07:54 UTC, codeliezel approved these changes

2020-11-14 07:56 UTC, merged