chore(env): setup dev environment
devcareer/code-jammers-backend pull request #6
Opened 2020-08-31 15:51 UTC by Fiyin-Anne

- install express and dotenv

[Delivers #174566170]

2020-08-31 18:58 UTC, bellogo commented
This meets the requirement to set development environment. well done Fiyin.

2020-08-31 19:04 UTC, bellogo approved these changes
This meets the requirement to set development environment. well done Fiyin.

2020-08-31 22:00 UTC, codeliezel reviewed
well done, so in order not to waste time @Fiyin-Anne  the 
- .env file should never be pushed and should be in gitignore

2020-08-31 22:08 UTC, codeliezel requested changes

2020-08-31 22:08 UTC, codeliezel commented on src/app.js
> +if (process.env.NODE_ENV !== 'production') {
remove this body of code, you do not need to set the environment for now.

2020-08-31 22:08 UTC, codeliezel commented on src/app.js
> +if (process.env.NODE_ENV !== 'production') {
remove all and not only that line..

2020-09-01 08:05 UTC, Bernard-Namangala approved these changes

2020-09-01 08:35 UTC, codeliezel reviewed
Also, your PR header should look like this: **#167750041Set up the development environment**

So moving forward, that is how PR headers should be like

After, your PR comment should contain these things:

**What does this PR do?**

**Description of tasks to be completed?**

**How should this be manually tested/checked?**

**What are the relevant pivotal tracker stories?**
#167750045 // this should be a link to the PT story like <a href=""> #167750045 </a>

2020-09-01 10:06 UTC, codeliezel approved these changes

2020-09-01 10:07 UTC, bellogo approved these changes
I confirmed that the right changes were made

2020-09-01 10:07 UTC, donaldcrane approved these changes
nice work!

2020-09-01 10:10 UTC, merged