#174566483 Set up the sequelize enviroment
devcareer/code-jammers-backend pull request #8
Opened 2020-09-01 12:39 UTC by donaldcrane

### What does this PR do?

This PR sets up the sequelize environment by adding sequelize and postgres packages.

### Description of tasks to be completed?

-  Install sequelize package
-  Install postgres package
-  install sequelize-cli package
   
### How should this be manually tested/checked?

-   Clone the PR
-   Cd into the branch ch-setup-seq-env-174566483
-   Install the dependencies using npm install
-   run sequelize init to create the enviroment
    
### What are the relevant pivotal tracker stories?

#174566483

2020-09-01 13:07 UTC, Fiyin-Anne reviewed
I followed the steps but `sequelize init` returns an error message saying `sequelize : The term 'sequelize' is not recognized as the name of a cmdlet, function, script file, or operable program`.

2020-09-01 13:14 UTC, donaldcrane commented
sequelize-cli should be installed globally, then run sequelize init (this should create the working enviroment files including the config file)

2020-09-01 13:16 UTC, Fiyin-Anne commented
> sequelize-cli should be installed globally, then run sequelize init (this should create the working enviroment files including the config file)

Please add this to your description.

2020-09-01 17:08 UTC, bellogo reviewed
After `npm install`
i ran: `sequelize init` and i got this

ERROR: The file config\config.json already exists. Run command with --force to overwrite it.

2020-09-01 20:51 UTC, AbonyiXavier commented
You are supposed to  create a .sequelizerc file in the root directory of your project, change config.json to config.js to enable us make use of our environment variables for database connection.

2020-09-02 09:43 UTC, donaldcrane commented
> 
> 
> After `npm install`
> i ran: `sequelize init` and i got this
> 
> ERROR: The file config\config.json already exists. Run command with --force to overwrite it.
> 
> Is this the expected behavior?

you are not expected to overwrite it  because i already created it, you could just modify the codes inside(so u could skip `sequelize init`

2020-09-02 11:15 UTC, donaldcrane commented
> 
> 
> You are supposed to create a .sequelizerc file in the root directory of the project, change config.json to config.js to enable us make use of our environment variables for the database connection.

i have done that

2020-09-02 12:52 UTC, Fiyin-Anne approved these changes

2020-09-02 13:00 UTC, bellogo approved these changes

2020-09-02 16:25 UTC, AbonyiXavier commented
There is one more package left to install, which is  sequelize-cli , this package will enable us to generate our models, migrations and seeders folders using this command npx sequelize-cli init.

2020-09-03 11:15 UTC, codeliezel commented on src/models/index.js
> +'use strict';
lint all your codes using augusta command ad=nd re-commit

2020-09-03 11:21 UTC, codeliezel requested changes
@donaldcrane  the configuration you did in the config/config.js is the wrong location, do it in the database/config file.

good job

2020-09-03 21:18 UTC, codeliezel commented
@donaldcrane you have not even done what I asked you to do, copy all the codes away from the config/config.js and add it to database/config.js

2020-09-03 21:19 UTC, codeliezel commented
@donaldcrane also in your pr description, npm install is enough, that will install all dependencies.. update your pr

2020-09-07 10:42 UTC, bellogo approved these changes

2020-09-07 10:44 UTC, Fiyin-Anne approved these changes

2020-09-07 11:43 UTC, Augusta-E approved these changes

2020-09-07 12:14 UTC, codeliezel approved these changes
Good job

2020-09-07 12:15 UTC, merged